TicketManage.WebSite/Controllers/TicketLaSaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManage.Entity.TicketManage;
using TicketManage.Repository.Models;
using TicketManage.WebSite.Filters;
using TieckManage.Biz.TicketLaSaManage;
using TieckManage.Biz.TicketManage;

namespace TicketManage.WebSite.Controllers
{
    [LoginCheck]
    public class TicketLaSaController : BaseController
    {
        private TicketLaSaBiz biz = new TicketLaSaBiz();


        public ActionResult TicketLaSaList(TicketLaSaPageModel model)
        {
            ViewBag.TicketManageNav = "active open";
            ViewBag.TicketLaSaList = "active";
            model.OperatorAuthNum = UserInfoModel.PageModel.AuthNum;
            if ((model.OperatorAuthNum & 2) == 2)
            {
                model.OperatorUserNoList = new List<int> { UserInfoModel.PageModel.SEQ };
            }
            else if ((model.OperatorAuthNum & 4) == 4)
            {
                model.OperatorUserNoList = biz.GetUserNoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ);
            }
            else if ((model.OperatorAuthNum & 8) == 8)
            {
                model.OperatorUserNoList = biz.GetUserNoByCompanySEQ(UserInfoModel.PageModel.CompanySEQ);
            }
            model.ModelList = biz.GetTicketLaSaByCondition(model);
            string pageCount = ConfigurationManager.AppSettings["PageCount"].ToString();
            model.ListCount = model.ModelList.Count;
            if (model.PageNum == 0)
            {
                model.PageNum = 1;
            }
            else
            {
                model.PageNum = model.PageNum;
            }
            if (model.PageSize == 0)
            {
                model.PageSize = Convert.ToInt32(pageCount);
            }
            else
            {
                model.PageSize = Convert.ToInt32(model.PageSize);
            }
            if (model.ModelList.Count() > model.PageSize)
            {
                model.PageTotal = model.ModelList.Count() % model.PageSize == 0 ? model.ModelList.Count() / model.PageSize : (model.ModelList.Count() / model.PageSize) + 1;
            }
            model.ModelList = model.ModelList.Skip(model.PageSize * (model.PageNum - 1)).Take(model.PageSize).ToList();

            return View(model);
        }

        public PartialViewResult TicketLaSaInfoManage(string id)
        {
            TicketLaSaPageModel pageModel = new TicketLaSaPageModel();
            if (id != "0")
            {
                pageModel.PageModel = biz.GetTickLasaInfo(Convert.ToInt32(id));
                pageModel.PageModel1 = biz.GetTickLasaInfo(Convert.ToInt32(id) + 1);
            }
            pageModel.OperatorAuthNum = UserInfoModel.PageModel.AuthNum;
            return PartialView(pageModel);
        }

        [HttpPost]
        public JsonResult SaveTicketLaSaInfo(TicketLaSaPageModel model)
        {
            JsonResult result = new JsonResult();
            bool res = false;

            decimal brokeragemoney = 0;//服务费1
            decimal brokeragemoney1 = 0;//服务费2
            decimal totalmoney = 0;//总收入

            brokeragemoney = Convert.ToDecimal((model.PageModel.TicketNum + model.PageModel.KidNum) * 5);
            brokeragemoney1 = Convert.ToDecimal((model.PageModel1.TicketNum + model.PageModel1.KidNum) * 5);
            model.PageModel1.CostMoney = model.PageModel.CostMoney;//毛利收入

            model.PageModel.Brokerage = brokeragemoney;//服务费
            model.PageModel1.Brokerage = brokeragemoney1;//服务费

            totalmoney = Convert.ToDecimal(brokeragemoney + brokeragemoney1 + model.PageModel.InsuranceMoney + model.PageModel1.InsuranceMoney + model.PageModel.CostMoney);

            model.PageModel.TotalMoney = totalmoney;//总收入
            model.PageModel1.TotalMoney = totalmoney;//总收入

            string groupno = Guid.NewGuid().ToString();
            model.PageModel.GroupNo = groupno;//组号
            model.PageModel1.GroupNo = groupno;//组号

            model.PageModel1.CreateTime = model.PageModel.CreateTime;
            model.PageModel1.StartDriveDate = model.PageModel.StartDriveDate;
            model.PageModel1.TicketWindow = model.PageModel.TicketWindow;
            model.PageModel1.OperatorName = model.PageModel.OperatorName;
            model.PageModel1.OperatorSEQ = UserInfoModel.PageModel.SEQ;
            res = biz.SaveInfo(model);
            if (res)
            {
                result.Data = "保存成功";
            }
            else
            {
                result.Data = "保存失败";
            }
            return result;
        }
        public JsonResult DeleteTicketLaSaInfo(string seq)
        {
            JsonResult result = new JsonResult();
            bool res = false;
            if (!string.IsNullOrEmpty(seq))
            {
                res = biz.DeleteInfo(Convert.ToInt32(seq));

            }
            if (res)
            {
                result.Data = "删除成功！";
            }
            else
            {
                result.Data = "删除失败！";
            }

            return result;
        }

    }
}

TicketManage.WebSite/Views/TicketLaSa/TicketLaSaInfoManage.cshtml
@model TicketLaSaPageModel
<div class="page-content" id="editdiv">
    <div class="row">
        <div class="col-lg-12">
            <form class="form-horizontal" action="TicketGroup/SaveTicketGroupInfo" method="post" role="form" id="salepoint-form" enctype="multipart/form-data">
                @Html.HiddenFor(p => p.PageModel.SEQ)
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 取票日期:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(a => a.PageModel.CreateTime, new { Value = Model.PageModel == null ? "" : (Model.PageModel.CreateTime.HasValue ? String.Format("{0:yyyy-MM-dd}", Model.PageModel.CreateTime) : ""), @class = "form-control", onfocus = "WdatePicker({dateFmt:'yyyy-MM-dd'})" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 取票窗口:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.TicketWindow, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 开车日期:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(a => a.PageModel.StartDriveDate, new { Value = Model.PageModel == null ? "" : (Model.PageModel.StartDriveDate.HasValue ? String.Format("{0:yyyy-MM-dd}", Model.PageModel.StartDriveDate) : ""), @class = "form-control", onfocus = "WdatePicker()" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 车次1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.TrainNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 发站1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.StartStation, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 到站1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.EndSation, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 席别1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.TicketCategoryCode, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 全票1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.TicketNum, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 孩票1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.KidNum, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 票卷起止号1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.StartTicketNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 客票收入1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.TicketMoney, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 乘意险收入1:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.InsuranceMoney, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 车次2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.TrainNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 发站2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.StartStation, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 到站2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.EndSation, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 席别2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.TicketCategoryCode, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 全票2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.TicketNum, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 孩票2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.KidNum, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 票卷起止号2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.StartTicketNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 客票收入2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.TicketMoney, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 乘意险收入2:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel1.InsuranceMoney, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 毛利收入:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.CostMoney, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 售票人员:</label>
                    <div class="col-sm-5">
                        @Html.TextBoxFor(p => p.PageModel.OperatorName, new { @class = "form-control" })
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

TicketManage.WebSite/Views/TicketLaSa/TicketLaSaList.cshtml
@model TicketLaSaPageModel
@{
    ViewBag.Title = "TicketLaSaList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var indexCount = 0;
}
@section HeaderScript{
    <link href="~/Scripts/skin/WdatePicker.css" rel="stylesheet" />
    <script src="~/Scripts/WdatePicker.js"></script>
    <script type="text/javascript">
    $(function () {
        ListPager("@Model.PageTotal", "@Model.PageNum", 10, 'TicketLaSa', 'TicketLaSaList');
        SaveInfo();

    });
    function ShowSaveInfo(obj) {
        $.ajax({
            url: "@Url.Action("TicketLaSaInfoManage", "TicketLaSa")",
            type: "post",
            data: { id: obj },
            async: false,
            success: function (json) {
                $("#ticketinfobody").html(json);
                $("#ticketinfomodal").modal({ backdrop: 'static', keyboard: false });
            }
        });
    }
    function SaveInfo() {
        $("#sumitForm").click(function () {
            $.ajax({
                url: "@Url.Action("SaveTicketLaSaInfo", "TicketLaSa")",
                    type: "post",
                    data: $("#salepoint-form").serialize(),
                    success: function (json) {
                        window.location.href = "@Url.Action("TicketLaSaList", "TicketLaSa")";
                        $("#ticketinfomodal").modal("toggle");
                    }
                });
            });
        }
        function DeleteInfo(obj) {
            if (confirm("是否确认删除这条数据")) {
                $.ajax({
                    url: "@Url.Action("SaveTicketLaSaInfo", "TicketLaSa")",
                type: "Post",
                data: { seq: obj },
                success: function (json) {
                    $("#TicketSearchForm").submit();
                    SaveInfo();
                },
                error: function () {

                }
            });
        }
    }
    </script>


}
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="@Url.Action("TicketLaSaList", "TicketLaSa")">销售数据管理</a>
        </li>
        <li>
            <a href="@Url.Action("TicketLaSaList", "TicketLaSa")">拉萨票管理</a>
        </li>
        <li class="active">拉萨票列表</li>
    </ul><!-- .breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            拉萨票列表
        </h1>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <div class="clearfix">
                    <form action="/TicketLaSa/TicketLaSaList" id="TicketSearchForm">
                        <div class="col-md-1" style="line-height: 33px; text-align: right"><label class="control-label no-padding-right">取票日期：</label></div>
                        <div class="col-md-1">
                            @Html.TextBoxFor(a => a.StartDate, new { @class = "form-control", onfocus = "WdatePicker()" })
                        </div>
                        <div class="col-md-1" style="text-align:left">
                            @Html.TextBoxFor(a => a.EndDate, new { @class = "form-control", onfocus = "WdatePicker()" })
                        </div>
                        <div class="col-md-5"></div>
                        <div class="col-md-4">
                            <button id="searchBtn" type="submit" class="btn btn-purple btn-sm">
                                <i class="icon-search icon-on-right bigger-110"></i>查询
                            </button>
                            @if ((Model.OperatorAuthNum != null && (Model.OperatorAuthNum & 2) == 2) || (Model.OperatorAuthNum & 1) == 1 || (Model.OperatorAuthNum & 16) == 16)
                            {
                                <button type="button" id="addUserBtn" class="btn btn-pink btn-sm" onclick="ShowSaveInfo(0)">数据录入</button>
                            }
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-xs-12">
                    <div class="table-responsive" id="tabList">
                        <table id="ticketListTable" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>取票日期</th>
                                    <th>取票窗口</th>
                                    <th>开车日期</th>
                                    <th>车次</th>
                                    <th>发站</th>
                                    <th>到站</th>
                                    <th>席别</th>
                                    <th>全票</th>
                                    <th>孩票</th>
                                    <th>票卷起止号</th>
                                    <th>客票收入</th>
                                    <th>服务费收入</th>
                                    <th>乘意险收入</th>
                                    <th>毛利收入</th>
                                    <th>总收入</th>
                                    <th>售票人员</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    foreach (var item in Model.ModelList)
                                    {
                                        string createtime = string.Empty;
                                        string startdrivedate = string.Empty;
                                        if (item.CreateTime.HasValue == true)
                                        {
                                            createtime = Convert.ToDateTime(item.CreateTime).ToString("yyyy-MM-dd");
                                        }
                                        if (item.StartDriveDate.HasValue == true)
                                        {
                                            startdrivedate = Convert.ToDateTime(item.StartDriveDate).ToString("yyyy-MM-dd");
                                        }
                                        indexCount++;
                                        <tr>
                                            <td>@item.SEQ</td>
                                            @{
                                        if (indexCount % 2 != 0)
                                        {
                                            <td rowspan="2">@createtime</td>
                                                <td rowspan="2">@item.TicketWindow</td>
                                                <td rowspan="2">@startdrivedate</td>
                                        }
                                            }
                                            <td>@item.TrainNo</td>
                                            <td>@item.StartStation</td>
                                            <td>@item.EndSation</td>
                                            <td>@item.TicketCategoryCode</td>
                                            @*<td>@item.TicketCategoryCodeName</td>*@
                                            <td>@item.TicketNum</td>
                                            <td>@item.KidNum</td>
                                            <td>@item.StartTicketNo</td>
                                            <td>@item.TicketMoney</td>
                                            <td>@item.Brokerage</td>
                                            <td>@item.InsuranceMoney</td>

                                            @{
                                        if (indexCount % 2 != 0)
                                        {
                                            <td rowspan="2">@item.CostMoney</td>
                                                <td rowspan="2">@item.TotalMoney</td>
                                                <td rowspan="2">@item.OperatorName</td>
                                                <td rowspan="2">
                                                    @if ((Model.OperatorAuthNum != null && (Model.OperatorAuthNum & 2) == 2) || (Model.OperatorAuthNum & 1) == 1 || (Model.OperatorAuthNum & 16) == 16)
                                                    {
                                                        <a class="btn btn-sm btn-warning" href="#" onclick="ShowSaveInfo('@item.SEQ')">编辑</a>
                                                        <a class="btn btn-sm btn-danger" href="#" onclick="DeleteInfo('@item.SEQ')">删除</a>
                                                    }
                                                </td>
                                        }
                                            }
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div><!-- /.table-responsive -->
                </div><!-- /span -->
            </div>
        </div>
        <div class="col-lg-12">
            <div class="row" style="background-color:#f5f5f5;border:1px solid #e3e3e3;margin-left:0px;margin-right:0px">
                <div class="col-xs-6">
                    <div style="color:#2283c5;padding-top:5px">
                        每页显示
                        <select id="pageShowCount" onchange="ChangePageShowCount('@Model.PageNum',this, 'TicketLaSa', 'TicketLaSaList')">
                            <option value="10" selected="selected">10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                            <option value="40">40</option>
                        </select>条记录
                    </div>
                </div>
                <div class="col-xs-6 text-right" style="padding-top:5px">
                    @Html.Hidden("totalCount", Model.ListCount)
                    <ul id='ticketlist-pager' style="cursor:pointer;margin:0px;line-height:33px"></ul>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="modal fade" id="ticketinfomodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    拉萨票信息
                </h4>
            </div>
            <div class="modal-body" id="ticketinfobody">

            </div>
            <div class="modal-footer" id="buttonList">
                <input type="button" id="sumitForm" class="btn btn-info btn-sm" style="margin-right:10px" value="保存" />
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>