TicketManage.WebSite/Controllers/UserInfoController.cs
using System;
using System.Web.Mvc;
using TicketManage.Entity.TicketManage;
using TicketManage.WebSite.Filters;
using TieckManage.Biz.TicketManage;
using System.Collections.Generic;
using TicketManage.WebSite.Models;
using TicketManage.Repository.Models;

namespace TicketManage.WebSite.Controllers
{
    [LoginCheck]
    public class UserInfoController : BaseController
    {
        private UserInfoManageBiz biz = new UserInfoManageBiz();

        /// <summary>
        /// 页面初始化
        /// </summary>
        /// <param name="model"></param>
        private void UserListManageInit(UserPageModel model)
        {
            ViewBag.BaseDataNav = "active open";
            ViewBag.PageNav = "active";
            model.OperatorAuthNum = UserInfoModel.PageModel.AuthNum;
            model.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", 10);
            var groupList = new List<KeyValueModel>();
            var tempCompanyList = new List<KeyValueModel>();
            var tempSalepointList = new List<KeyValueModel>();
            ViewBag.IsAdmin = UserInfoModel.IsAdmin ? "true" : "false";
            if ((UserInfoModel.PageModel.AuthNum & 4) == 4)
            {
                groupList.AddRange(biz.GetGroupInfoById(UserInfoModel.PageModel.GroupSEQ ?? 0));
                var tempCompanyListSource = biz.GetCompanyInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0);
                tempCompanyListSource.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempCompanyList.AddRange(tempCompanyListSource);
                var tempSalepointListSource = biz.GetSalePointInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0);
                tempSalepointListSource.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempSalepointList.AddRange(tempSalepointListSource);
            }
            else if ((UserInfoModel.PageModel.AuthNum & 8) == 8)
            {
                groupList.AddRange(biz.GetGroupInfoById(UserInfoModel.PageModel.GroupSEQ ?? 0));
                tempCompanyList.AddRange(biz.GetCompanyInfoById(UserInfoModel.PageModel.CompanySEQ ?? 0));
                var tempSalepointListSource = biz.GetSalePointInfoByCompanySEQ(UserInfoModel.PageModel.CompanySEQ ?? 0);
                tempSalepointListSource.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempSalepointList.AddRange(tempSalepointListSource);
            }
            else if ((UserInfoModel.PageModel.AuthNum & 1) == 1 || (UserInfoModel.PageModel.AuthNum & 16) == 16)
            {
                groupList.AddRange(biz.GetGroupInfoByAll());
                groupList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempCompanyList.AddRange(biz.GetCompanyInfoByAll());
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempSalepointList.AddRange(biz.GetSalePointInfoByAll());
                tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }


            model.PageModel.CompanySEQ = UserInfoModel.PageModel.CompanySEQ ?? 0;
            model.PageModel.SalePointSEQ = UserInfoModel.PageModel.SalePointSEQ ?? 0;

            model.GroupSource = new SelectList(groupList, "Key", "Value");
            model.CompanySource = new SelectList(tempCompanyList, "Key", "Value");
            model.SalePointSource = new SelectList(tempSalepointList, "Key", "Value");
        }

        [HttpGet]
        public ActionResult UserListManage()
        {
            var pageModel = new UserPageModel() { PageSize = 10, CurrentPage = 1, PageModel = new UserInfo() };
            UserListManageInit(pageModel);
            if ((UserInfoModel.PageModel.AuthNum & 4) == 4)
            {
                pageModel.PageModel.GroupSEQ = UserInfoModel.PageModel.GroupSEQ;
            }
            else if ((UserInfoModel.PageModel.AuthNum & 8) == 8)
            {
                pageModel.PageModel.CompanySEQ = UserInfoModel.PageModel.CompanySEQ;
            }
            pageModel.CurrentUserNo = UserInfoModel.PageModel.UserNo;
            pageModel.ListModel = biz.GetUserInfoListByCondition(pageModel);
            return View(pageModel);
        }

        [HttpPost]
        public ActionResult UserListManage(UserPageModel model)
        {
            model.ListModel = biz.GetUserInfoListByCondition(model);
            UserListManageInit(model);
            return View(model);
        }

        [HttpGet]
        public ActionResult UserInfoManage(int id)
        {
            ViewBag.BaseDataNav = "active open";
            ViewBag.PageNav = "active";
            var pageModel = new UserPageModel();
            return View(pageModel);
        }

        [HttpPost]
        public ActionResult UserInfoManage(UserPageModel model)
        {
            ViewBag.BaseDataNav = "active open";
            ViewBag.PageNav = "active";
            return View(model);
        }


        [AjaxOnly]
        public JsonResult UserInfoPasswordReset(int id)
        {
            var result = biz.ResetPasswordByUserInfoSEQ(id);
            return Json(result ? "操作完成！" : "操作失败！", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult UserInfoDel(int id)
        {
            var result = biz.DeleteUserInfoByEntity(id);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取指定集团下单位信息
        /// </summary>
        /// <param name="id">集团序号</param>
        /// <returns></returns>
        [HttpGet]
        public PartialViewResult ShowCompanyByGroupSEQ(int id)
        {
            var pageModel = new SelectPageModel();
            pageModel.ControlId = "PageModel_CompanySEQ";
            pageModel.ControlName = "PageModel.CompanySEQ";
            if (id != 0)
            {
                var pageModelList = biz.GetCompanyInfoByGroupSEQ(id);
                if (pageModelList.Count == 0
                    || (UserInfoModel.PageModel.AuthNum & 1) == 1
                    || (UserInfoModel.PageModel.AuthNum & 4) == 4
                    || (UserInfoModel.PageModel.AuthNum & 8) == 8
                    || (UserInfoModel.PageModel.AuthNum & 16) == 16
                    || (UserInfoModel.PageModel.AuthNum & 32) == 32)
                {
                    pageModelList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                }
                var selectSource = new SelectList(pageModelList, "Key", "Value");
                pageModel.SelectSource = selectSource;
            }
            else
            {
                var pageModelList = new List<KeyValueModel>();
                pageModelList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                var selectSource = new SelectList(pageModelList, "Key", "Value");
                pageModel.SelectSource = selectSource;
            }
            return PartialView("_PartialSelectList", pageModel);
        }

        /// <summary>
        /// 获取指定单位下代售点信息
        /// </summary>
        /// <param name="id">单位序号</param>
        /// <returns></returns>
        [HttpGet]
        public PartialViewResult ShowSalePointByCompanySEQ(int id)
        {
            var pageModel = new SelectPageModel();
            pageModel.ControlId = "PageModel_SalePointSEQ";
            pageModel.ControlName = "PageModel.SalePointSEQ";
            if (id != 0)
            {
                var pageModelList = biz.GetSalePointInfoByCompanySEQ(id);
                pageModelList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                var selectSource = new SelectList(pageModelList, "Key", "Value");
                pageModel.SelectSource = selectSource;
            }
            else
            {
                var pageModelList = new List<KeyValueModel>();
                pageModelList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                var selectSource = new SelectList(pageModelList, "Key", "Value");
                pageModel.SelectSource = selectSource;
            }

            return PartialView("_PartialSelectList", pageModel);
        }

        [HttpGet]
        public ActionResult UserInfoAdd()
        {
            var pageModel = new UserPageModel();
            pageModel.AuthListSource = new SelectList(AuthNumSource, "Key", "Value");
            pageModel.SexSource = new SelectList(SexSource, "Key", "Value");

            var groupList = new List<KeyValueModel>();
            var tempCompanyList = new List<KeyValueModel>();
            var tempSalepointList = new List<KeyValueModel>();
            if (UserInfoModel.IsAdmin)
            {
                groupList.AddRange(biz.GetGroupInfoByAll());
                tempCompanyList.AddRange(biz.GetCompanyInfoByAll());
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                tempSalepointList.AddRange(biz.GetSalePointInfoByAll());
                tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                ViewBag.IsAdmin = "true";
            }
            else
            {
                groupList.AddRange(biz.GetGroupInfoById(UserInfoModel.PageModel.GroupSEQ ?? 0));
                if ((UserInfoModel.PageModel.AuthNum & 4) == 4)
                {
                    tempCompanyList.AddRange(biz.GetCompanyInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0));
                    tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                    tempSalepointList.AddRange(biz.GetSalePointInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0));
                    tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
                }

TicketManage.WebSite/Controllers/UserInfoOtherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManage.Entity.CommonManage;
using TicketManage.Entity.OtherUserManage;
using TicketManage.Repository.Models;
using TicketManage.WebSite.Filters;
using TieckManage.Biz.OtherUserManage;

namespace TicketManage.WebSite.Controllers
{
    [LoginCheck]
    public class UserInfoOtherController : BaseController
    {
        /// <summary>
        /// 用户操作业务实例
        /// </summary>
        private UserInfoOtherBiz biz = new UserInfoOtherBiz();

        /// <summary>
        /// 列表页面初始化
        /// </summary>
        /// <param name="model"></param>
        private void UserInfoListInit(UserInfoOtherPageModel model)
        {
            switch (model.SystemName)
            {
                case TicketManage.Entity.CommonManage.SystemName.票务管理系统:
                    break;
                case TicketManage.Entity.CommonManage.SystemName.地接管理系统:
                    ViewBag.TravelLocalAgencyNav = "active open";
                    break;
                case TicketManage.Entity.CommonManage.SystemName.导游管理系统:
                    ViewBag.GuideInfoNav = "active open";
                    break;
                case TicketManage.Entity.CommonManage.SystemName.宣传品管理系统:
                    ViewBag.PublicityNav = "active open";
                    break;
                case TicketManage.Entity.CommonManage.SystemName.工效管理系统:
                    ViewBag.KPIDataNav = "active open";
                    break;
            }
            ViewBag.UserInfoListNav = "active";
            model.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", model.PageSize);
        }

        [HttpGet]
        public ActionResult UserInfoList()
        {
            var flagSystem = Request.QueryString["systemName"];
            var model = new UserInfoOtherPageModel() { PageSize = 10, CurrentPage = 1, OperatorAuthNum = CommonUserInfoModel.PageModel.AuthNum };
            var systemEnumVal = ConvertSystemName(flagSystem);
            if (systemEnumVal != 0)
            {
                model.SystemName = systemEnumVal;
                model.MessageState = false;
                UserInfoListInit(model);
                model.ModelList = biz.GetUserInfoOtherListByCondition(model);
            }
            else
            {
                model.MessageState = true;
                model.Message = "参数错误！";
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult UserInfoList(UserInfoOtherPageModel model)
        {
            UserInfoListInit(model);
            model.ModelList = biz.GetUserInfoOtherListByCondition(model);
            return View(model);
        }

        [AjaxOnly]
        public PartialViewResult ShowUserInfoOther(string systemName)
        {
            var model = new UserInfoOtherPageModel();
            var systemEnumVal = ConvertSystemName(systemName);
            if (systemEnumVal != 0)
            {
                model.AuthListSource = new SelectList(AuthNumSourceBySystem(systemEnumVal), "Key", "Value");
            }
            else
            {
                model.AuthListSource = new SelectList(new Dictionary<string, string> { { "", "" } }, "Key", "Value");
            }
            var tempCompanyList = new List<KeyValueModel>();
            var tempList = biz.GetOtherUserCompany();
            if (tempList != null && tempList.Count > 0)
            {
                tempCompanyList.AddRange(biz.GetOtherUserCompany());
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }
            else
            {
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "" });
            }
            model.CompanySource = new SelectList(tempCompanyList, "Key", "Value");
            model.SexSource = new SelectList(SexSource, "Key", "Value");
            model.SystemName = systemEnumVal;
            return PartialView(model);
        }

        [AjaxOnly]
        public PartialViewResult ShowUserInfoOtherByEdit(string systemName, int id)
        {
            var model = new UserInfoOtherPageModel();
            model.PageModel = biz.GetUserInfoOtherBySEQ(id);
            var systemEnumVal = ConvertSystemName(systemName);
            if (systemEnumVal != 0)
            {
                var tempListSource = AuthNumSourceBySystem(systemEnumVal);

                var indexFlag = 0;
                foreach (var item in tempListSource)
                {
                    if (((model.PageModel.AuthNum ?? 0) & Convert.ToInt32(item.Key)) != 0)
                    {
                        model.PageModel.AuthNum = Convert.ToInt32(item.Key);
                        indexFlag++;
                    }
                }
                if (indexFlag == 0)
                {
                    tempListSource.Add("0", string.Empty);
                }
                model.AuthListSource = new SelectList(tempListSource.OrderBy(a => a.Key), "Key", "Value");
            }
            else
            {
                model.AuthListSource = new SelectList(new Dictionary<string, string> { { "", "" } }, "Key", "Value");
            }
            var tempCompanyList = new List<KeyValueModel>();
            var templist = biz.GetOtherUserCompany();
            if (templist != null && templist.Count > 0)
            {
                tempCompanyList.AddRange(templist);
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }
            else
            {
                tempCompanyList.Insert(0, new KeyValueModel { Key = 0, Value = "" });
            }
            model.CompanySource = new SelectList(tempCompanyList, "Key", "Value");
            model.SexSource = new SelectList(SexSource, "Key", "Value");
            model.SystemName = systemEnumVal;
            return PartialView("ShowUserInfoOther", model);
        }



        [AjaxOnly]
        public JsonResult EditUserInfoOther(UserInfoOtherPageModel model)
        {
            model.AuthList = AuthNumSourceBySystem(model.SystemName);
            var result = biz.EditUserInfoOther(model);
            return Json(new { result = result, message = model.Message });
        }

        [AjaxOnly]
        public JsonResult UserInfoPasswordReset(int id)
        {
            var result = biz.ResetPasswordByUserInfoSEQ(id);
            return Json(result ? "操作完成！" : "操作失败！", JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        public JsonResult UserInfoDel(int id)
        {
            var result = biz.DeleteUserInfoOther(id);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            var model = CommonUserInfoModel;
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangePassword(UserLoginPageModel model)
        {
            var result = biz.ChangePassWord(model);
            return View(model);
        }
    }
}

TicketManage.WebSite/Views/UserInfoOther/ChangePassword.cshtml
@model TicketManage.Entity.CommonManage.UserLoginPageModel
@{
    ViewBag.Title = "修改密码";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    var pageMessageStr = Model.MessageState ? "success" : "warning";
}
@section HeaderScript{
    <script type="text/javascript">
        $(function () {
            $("#SaveBut").click(function () {
                var oldPassWord = $("#OldPassword").val();
                var newPassWord = $("#PageModel_UserPassword").val();
                var conPassWord = $("#ConfirmPassword").val();
                if (oldPassWord != "") {
                    if (newPassWord != "") {
                        if (conPassWord != "") {
                            if (newPassWord == conPassWord) {
                                $("#ChangePasswordForm").submit();
                            } else {
                                alert("新密码和确认密码不正确！");
                            }
                        } else {
                            alert("确认密码不能为空！");
                        }
                    } else {
                        alert("新密码不能为空！");
                    }
                } else {
                    alert("旧密码不能为空！");
                }
            });

        })
    </script>
}
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="@Url.Action("Index","Home")">首页</a>
        </li>

        <li>
            <a href="@Url.Action("ChangePassword","UserInfoOther")">个人信息设置</a>
        </li>
        <li class="active">修改密码</li>
    </ul><!-- .breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>修改密码</h1>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @if (!String.IsNullOrEmpty(Model.Message))
            {
                <div class="alert alert-block alert-@pageMessageStr">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <i class="icon-ok @pageMessageStr"></i>
                    <strong class="@pageMessageStr">
                        @Model.Message
                    </strong>
                </div>
            }
            <form class="form-horizontal" role="form" method="post" id="ChangePasswordForm" action="@Url.Action("ChangePassword", "UserInfoOther")">
                @Html.HiddenFor(a => a.PageModel.SEQ)
                @Html.HiddenFor(a => a.PageModel.UserNo)
                @Html.HiddenFor(a => a.PageModel.UserName)
                <div class="form-group">
                    <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 旧密码 </label>
                    <div class="col-sm-11">
                        @Html.PasswordFor(a => a.OldPassword, new { @class = "col-xs-10 col-sm-5" })
                    </div>
                </div>
                <div class="space-4"></div>
                <div class="form-group">
                    <label class="col-sm-1 control-label no-padding-right" for="form-field-2"> 新密码 </label>
                    <div class="col-sm-11">
                        @Html.PasswordFor(a => a.PageModel.UserPassword, new { @class = "col-xs-10 col-sm-5" })
                    </div>
                </div>

                <div class="space-4"></div>
                <div class="form-group">
                    <label class="col-sm-1 control-label no-padding-right" for="form-field-2"> 确认密码 </label>
                    <div class="col-sm-11">
                        @Html.PasswordFor(a => a.ConfirmPassword, new { @class = "col-xs-10 col-sm-5" })
                    </div>
                </div>
                <div class="clearfix form-actions">
                    <div class="col-md-offset-1 col-md-11">
                        <button class="btn btn-info" type="button" id="SaveBut">
                            <i class="icon-ok bigger-110"></i>
                            保存
                        </button>
                        &nbsp; &nbsp; &nbsp;
                        <button class="btn" type="reset">
                            <i class="icon-undo bigger-110"></i>
                            重置
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

TicketManage.WebSite/Views/UserInfoOther/ShowUserInfoOther.cshtml
@model TicketManage.Entity.OtherUserManage.UserInfoOtherPageModel
<div id="addModelArea" class="page-content">
    <div class="row">
        <div class="col-lg-12">
            <form class="form-horizontal" action="@Url.Action("UserInfoAdd","UserInfo")" method="post" role="form" id="addModelForm">
                @Html.HiddenFor(a => a.PageModel.SEQ)
                @Html.HiddenFor(a => a.SystemName)
                @Html.HiddenFor(a => a.PageModel.UserPassword)
                @Html.HiddenFor(a => a.PageModel.UserState)
                @Html.HiddenFor(a => a.PageModel.CreateTime)
                @Html.HiddenFor(a => a.PageModel.CompanyName)
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">分公司：</label>
                    <div class="col-sm-9">

                        @Html.DropDownListFor(a => a.PageModel.CompanySEQ, Model.CompanySource, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">登录名：</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(a => a.PageModel.UserNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">姓名：</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(a => a.PageModel.UserName, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">身份证号：</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(a => a.PageModel.PassportNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">联系电话：</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(a => a.PageModel.ContactNo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">年龄：</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(a => a.PageModel.Age, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">性别：</label>
                    <div class="col-sm-9">
                        @Html.DropDownListFor(a => a.PageModel.Sex, Model.SexSource, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">权限信息：</label>
                    <div class="col-sm-9">
                        @Html.DropDownListFor(a => a.PageModel.AuthNum, Model.AuthListSource, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red;text-align:left">默认密码为000000</label>
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red" id="MessageArea"></label>
                </div>
            </form>
        </div>
    </div>
</div>