TicketManage.WebSite/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManage.Entity.TicketManage;
using TicketManage.WebSite.Filters;
using TicketManage.WebSite.Logic;
using TieckManage.Biz.TicketManage;
namespace TicketManage.WebSite.Controllers
{
    [LoginCheck]
    public class ReportController : BaseController
    {
        public ActionResult GroupReportByDay()
        {
            ViewBag.ReportNav = "active open";
            ViewBag.GroupReportByDay = "active";
            var pageModel = new UserPageModel();
            pageModel.PageModel = UserInfoModel.PageModel;
            return View(pageModel);
        }

        public ActionResult GroupReportByMonth()
        {
            ViewBag.ReportNav = "active open";
            ViewBag.GroupReportByMonth = "active";
            return View();
        }

        public ActionResult GroupReportByWeek()
        {
            ViewBag.ReportNav = "active open";
            ViewBag.GroupReportByWeek = "active";
            return View();
        }

        public PartialViewResult AddTicketPlan(string id, string YearStr)
        {
            TicketPlanManageBiz biz = new TicketPlanManageBiz();
            TicketPlanPageModel model = new TicketPlanPageModel();
            TicketManageLogic Logic = new TicketManageLogic();
            CompanyInfoManageBiz comBiz = new CompanyInfoManageBiz();
            if (string.IsNullOrEmpty(YearStr))
            {
                YearStr = DateTime.Now.Year.ToString();
            }
            model.PageModel = biz.GetTicketPlan(Convert.ToInt32(id), YearStr);
            model.YearList = new List<SelectListItem> { 
            new  SelectListItem{Text = DateTime.Now.Year.ToString(),Value = DateTime.Now.Year.ToString(),Selected=true},
            new  SelectListItem{Text = (DateTime.Now.Year-1).ToString(),Value = DateTime.Now.Year.ToString()},
            new  SelectListItem{Text = (DateTime.Now.Year-2).ToString(),Value = DateTime.Now.Year.ToString()},
            new  SelectListItem{Text = (DateTime.Now.Year-3).ToString(),Value = DateTime.Now.Year.ToString()},
            new  SelectListItem{Text = (DateTime.Now.Year-4).ToString(),Value = DateTime.Now.Year.ToString()},
            };
            model.CompanyList = Logic.ConvertUnitList(comBiz.GetCompanyInfoListByAll());
            return PartialView(model);
        }

        public JsonResult SaveTicketPlan(TicketPlanPageModel model)
        {
            JsonResult result = new JsonResult();
            TicketPlanManageBiz biz = new TicketPlanManageBiz();
            if (model.PageModel != null)
            {
                model.PageModel.CreateTime = DateTime.Now;
            }
            result.Data = biz.SaveTicketPlan(model);
            return result;

        }
        [HttpPost, AjaxOnly]
        public JsonResult LoadAddTicketPlan(string id, string YearStr)
        {
            TicketPlanManageBiz biz = new TicketPlanManageBiz();
            TicketPlanPageModel model = new TicketPlanPageModel();
            TicketManageLogic Logic = new TicketManageLogic();
            CompanyInfoManageBiz comBiz = new CompanyInfoManageBiz();
            if (string.IsNullOrEmpty(YearStr))
            {
                YearStr = DateTime.Now.Year.ToString();
            }
            JsonResult result = new JsonResult();
            result.Data = biz.GetTicketPlan(Convert.ToInt32(id), YearStr);
            return result;
        }

        public ActionResult TicketIncomManage()
        {
            ViewBag.ReportNav = "active open";
            ViewBag.TicketIncomManage = "active";
            return View();
        }
    }

}

TicketManage.WebSite/Controllers/TicketController.cs
using System;
using System.Web.Mvc;
using TicketManage.Entity.TicketManage;
using TicketManage.Repository.Models;
using TicketManage.WebSite.Filters;
using System.Collections.Generic;
using TieckManage.Biz.TicketManage;
using TicketManage.Entity.CommonManage;

namespace TicketManage.WebSite.Controllers
{
    /// <summary>
    /// Description of TicketController.
    /// </summary>
    [LoginCheck]
    public class TicketController : BaseController
    {
        private TicketManageBiz biz = new TicketManageBiz();
        private TicketUnionBiz uBiz = new TicketUnionBiz();
        private UserInfoManageBiz userInfoBiz = new UserInfoManageBiz();

        #region 票务业务相关

        /// <summary>
        /// 初始化查询区域需要数据源
        /// </summary>
        /// <param name="pageModel"></param>
        private void InitIndex(TicketIndexPageModel pageModel)
        {
            ViewBag.TicketManageNav = "active open";
            ViewBag.TicketNav = "active";
            var tempCompanyList = new List<KeyValueModel>();
            var tempSalepointList = new List<KeyValueModel>();
            ViewBag.IsAdmin = UserInfoModel.IsAdmin ? "true" : "false";
            if ((UserInfoModel.PageModel.AuthNum & 4) == 4)
            {
                tempCompanyList.AddRange(biz.GetCompanyInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0));
                if (tempCompanyList != null && tempCompanyList.Count > 0)
                {
                    tempSalepointList.AddRange(biz.GetSalePointInfoByGroupSEQ(UserInfoModel.PageModel.GroupSEQ ?? 0));
                }
                tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }
            else if ((UserInfoModel.PageModel.AuthNum & 8) == 8)
            {
                tempCompanyList.AddRange(biz.GetCompanyInfoById(UserInfoModel.PageModel.CompanySEQ ?? 0));
                if (tempCompanyList.Count > 0 && pageModel.CompanySEQ == null)
                {
                    pageModel.CompanySEQ = tempCompanyList[0].Key;
                }
                if (tempCompanyList != null && tempCompanyList.Count > 0)
                {
                    tempSalepointList.AddRange(biz.GetSalePointInfoByCompanySEQ(UserInfoModel.PageModel.CompanySEQ ?? 0));
                }
                tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }
            else if ((UserInfoModel.PageModel.AuthNum & 2) == 2)
            {
                tempCompanyList.AddRange(biz.GetCompanyInfoById(UserInfoModel.PageModel.CompanySEQ ?? 0));
                if (tempCompanyList.Count > 0 && pageModel.CompanySEQ == null)
                {
                    pageModel.CompanySEQ = tempCompanyList[0].Key;
                }
                if (tempCompanyList != null && tempCompanyList.Count > 0)
                {
                    tempSalepointList.AddRange(biz.GetSalePointInfoById(UserInfoModel.PageModel.SalePointSEQ ?? 0));
                    if (tempSalepointList.Count > 0 && pageModel.SalePointSEQ == 0)
                    {
                        pageModel.SalePointSEQ = tempSalepointList[0].Key;
                    }
                }
            }
            else if ((UserInfoModel.PageModel.AuthNum & 1) == 1
                || (UserInfoModel.PageModel.AuthNum & 16) == 16
                || (UserInfoModel.PageModel.AuthNum & 32) == 32)
            {
                tempCompanyList.Add(new KeyValueModel { Key = 0, Value = "全部" });
                tempCompanyList.AddRange(biz.GetCompanyInfoByAll());
                tempSalepointList.AddRange(biz.GetSalePointInfoByAll());
                tempSalepointList.Insert(0, new KeyValueModel { Key = 0, Value = "全部" });
            }

            pageModel.CompanySource = new SelectList(tempCompanyList, "Key", "Value");
            pageModel.SalePointSource = new SelectList(tempSalepointList, "Key", "Value");
            pageModel.TimeCategorySource = new SelectList(TimeCategorySource, "Key", "Value");
            pageModel.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", pageModel.PageSize);
            pageModel.OperatorAuthNum = UserInfoModel.PageModel.AuthNum;
            pageModel.DivideInto = biz.GetDivideIntoByUserSEQ(UserInfoModel.PageModel.SEQ);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var pageModel = new TicketIndexPageModel() { PageSize = 10, CurrentPage = 1, PageModel = new TicketCustomer() { OperationSEQ = UserInfoModel.PageModel.SEQ } };
            InitIndex(pageModel);
            pageModel.StartDate = DateTime.Now.ToString("yyyy-MM-dd");
            pageModel.EndDate = DateTime.Now.ToString("yyyy-MM-dd");
            pageModel.ModelList = biz.GetTicketByCondition(pageModel);
            Session["TicketIndexModel"] = pageModel;
            return View(pageModel);
        }

        [HttpPost]
        public ActionResult Index(TicketIndexPageModel model)
        {
            InitIndex(model);
            model.ModelList = biz.GetTicketByCondition(model);
            model.CurrentPage = model.CurrentPage;
            Session["TicketIndexModel"] = model;
            return View(model);
        }

        [HttpGet, LoginCheck]
        public ActionResult TicketDetail(int id, string dateTime)
        {
            ViewBag.TicketManageNav = "active open";
            ViewBag.TicketNav = "active";
            if (UserInfoModel.IsAdmin)
            {
                ViewBag.IsAdmin = "true";
            }
            else
            {
                ViewBag.IsAdmin = "false";
            }
            var pageModel = new TicketIndexPageModel();
            pageModel.PageSize = 10;
            pageModel.CurrentPage = 1;
            pageModel.SalePointSEQ = id;
            pageModel.OperaotrDate = dateTime;
            pageModel.ModelList = biz.GetTicketDetailByCondition(pageModel);
            pageModel.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", pageModel.PageSize);
            return View(pageModel);
        }

        [HttpPost, LoginCheck]
        public ActionResult TicketDetail(TicketIndexPageModel pageModel)
        {
            ViewBag.TicketManageNav = "active open";
            ViewBag.TicketNav = "active";
            if (UserInfoModel.IsAdmin)
            {
                ViewBag.IsAdmin = "true";
            }
            else
            {
                ViewBag.IsAdmin = "false";
            }
            pageModel = new TicketIndexPageModel();
            pageModel.PageSize = Convert.ToInt32(Request.Form["PageSize"]);
            pageModel.CurrentPage = Convert.ToInt32(Request.Form["CurrentPage"]);
            pageModel.SalePointSEQ = Convert.ToInt32(Request.Form["SalePointSEQ"]);
            pageModel.OperaotrDate = Request.Form["OperaotrDate"];
            pageModel.ModelList = biz.GetTicketDetailByCondition(pageModel);
            pageModel.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", pageModel.PageSize);
            return View(pageModel);
        }

        [HttpGet]
        public PartialViewResult TicketAdd()
        {
            var pageModel = new TicketIndexPageModel();
            pageModel.PageModel = new TicketCustomer();
            pageModel.PageModel.OperationSEQ = UserInfoModel.PageModel.SEQ;
            var tempUserModel = userInfoBiz.GetUserInfoById(pageModel.PageModel.OperationSEQ ?? 0);
            pageModel.OperatorUserNo = tempUserModel.UserNo;
            pageModel.OperatorUserName = tempUserModel.UserName;
            pageModel.OperaotrDate = DateTime.Now.ToString("yyyy-MM-dd");
            pageModel.DivideInto = biz.GetDivideIntoByUserSEQ(UserInfoModel.PageModel.SEQ);
            pageModel.PageModel.DivideInto = pageModel.DivideInto;
            return PartialView("_PartialTicketAdd", pageModel);
        }

        [HttpPost]
        public ActionResult TicketAdd(TicketIndexPageModel model)
        {
            ViewBag.TicketManageNav = "active open";
            ViewBag.TicketNav = "active";
            biz.DelTicketUser(model.OperatorUserNo, model.OperaotrDate);
            model.PageModel.CreateTime = Convert.ToDateTime(model.OperaotrDate);
            if (
                model.TicketNum1 == 0 && string.IsNullOrEmpty(model.PageModel.StartTicketNo) && string.IsNullOrEmpty(model.PageModel.EndTicketNo)
                && model.TicketNum2 == 0 && string.IsNullOrEmpty(model.PageModel.StartTicketNo2) && string.IsNullOrEmpty(model.PageModel.EndTicketNo2))
            {
                model.PageModel.TicketNum = 0;
            }
            else
            {
                model.PageModel.TicketNum = model.TicketNum1 + model.TicketNum2 + 1;
            }
            var result = biz.AddTicket(model);
            var resultList = FileUpload(Request);
            biz.AddKidTicket(model.PageModel.SEQ, resultList);
            model = Session["TicketIndexModel"] as TicketIndexPageModel;
            model.ModelList = biz.GetTicketByCondition(model);
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult TicketEdit(TicketIndexPageModel model)
        {
            var result = biz.EditTicket(model);
            var resultList = FileUpload(Request);
            model.PageModel.TicketNum = model.TicketNum1 + model.TicketNum2 + 1;
            biz.AddKidTicket(model.PageModel.SEQ, resultList);
            return RedirectToAction("TicketDetail", new { id = model.SalePointSEQ, dateTime = model.OperaotrDate });
        }

        [HttpGet]
        public PartialViewResult TicketEdit(int id, int SalePointSEQ, string OperatorDate)
        {
            var pageModel = new TicketIndexPageModel();
            pageModel.OperaotrDate = OperatorDate;
            pageModel.SalePointSEQ = SalePointSEQ;

TicketManage.WebSite/Views/Shared/_Layout.cshtml
@{
    var AuthNum = 0;
    if (ViewBag.AuthNum != null)
    {
        AuthNum = Convert.ToInt32(ViewBag.AuthNum);
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>票务管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- basic styles -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/Content/fileinput.min.css" rel="stylesheet" />
    <link href="~/Content/summernote.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.0.0.min.js"></script>
    <link rel="stylesheet" href="~/Content/css/ace.min.css" />
    <link rel="stylesheet" href="~/Content/css/ace-rtl.min.css" />
    <link rel="stylesheet" href="~/Content/css/ace-skins.min.css" />
    <script src="~/Scripts/fileinput.js"></script>
    <script src="~/Content/js/ace-extra.min.js"></script>
    <script src="~/Scripts/fileinput_locale_zh.js"></script>
    <script src="~/Scripts/bootstrap-paginator.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>
    <script src="~/Scripts/summernote.js"></script>
    <script src="~/Scripts/Common.js"></script>
    @RenderSection("HeaderScript", false)
    <style type="text/css">
        .rowPagetion {
            background-color: #f5f5f5;
            border: 1px solid #e3e3e3;
            margin-left: 0px;
            margin-right: 0px;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-default" id="navbar">
        <div class="navbar-container" id="navbar-container">
            <!--头部左侧导航-->
            <div class="navbar-header pull-left">
                <a href="@Url.Action("Index","Home")" class="navbar-brand">
                    <small>
                        <i class="icon-leaf"></i>
                        票务管理系统
                    </small>
                </a>
            </div>
            <!--头部左侧导航-->
            <!--头部右侧导航-->
            @Html.Partial("_PartialTopNav")
            <!--头部右侧导航-->
        </div>
    </div>
    <div class="main-container" id="main-container">
        <div class="main-container-inner">
            <a class="menu-toggler" id="menu-toggler" href="#">
                <span class="menu-text"></span>
            </a>
            <div class="sidebar" id="sidebar">
                <!--左侧导航-->
                @Html.Partial("_PartialLeftNav", AuthNum)
                <!--左侧导航-->
                <div class="sidebar-collapse" id="sidebar-collapse">
                    <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
                </div>
            </div>
            <div class="main-content">
                @RenderBody()
               
            </div>
        </div>
    </div>

    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/typeahead-bs2.min.js"></script>
    <script src="~/Content/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="~/Content/js/jquery.ui.touch-punch.min.js"></script>
    <script src="~/Content/js/jquery.slimscroll.min.js"></script>
    <script src="~/Content/js/jquery.easy-pie-chart.min.js"></script>
    <script src="~/Content/js/jquery.sparkline.min.js"></script>
    <script src="~/Content/js/flot/jquery.flot.min.js"></script>
    <script src="~/Content/js/flot/jquery.flot.pie.min.js"></script>
    <script src="~/Content/js/flot/jquery.flot.resize.min.js"></script>

    <!-- ace scripts -->

    <script src="~/Content/js/ace-elements.min.js"></script>
    <script src="~/Content/js/ace.min.js"></script>

    <!-- inline scripts related to this page -->

    
    @RenderSection("FooterScript", false)
</body>
</html>

TicketManage.WebSite/Views/Shared/_LayoutDataBaseManage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/assets/css/ace.min.css" rel="stylesheet" />
    <script src="~/Content/assets/js/jquery-2.0.3.min.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    @RenderSection("HeaderScript", false)
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("FooterScript", false)
</body>
</html>

TicketManage.WebSite/Views/Shared/_LayoutMobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-2.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    @RenderSection("HeaderScript", false)
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("FooterScript", false)
</body>
</html>

TicketManage.WebSite/Views/Shared/_PartialLeftNav.cshtml
@model System.Int32
<ul class="nav nav-list">

    @if ((Model & 1) == 1 || (Model & 2) == 2 || (Model & 4) == 4 || (Model & 8) == 8 || (Model & 16) == 16 || (Model & 32) == 32)
    {
        <li class="@ViewBag.TicketManageNav">
            <a href="#" class="dropdown-toggle">
                <i class="icon-desktop"></i>
                <span class="menu-text"> 销售数据管理 </span>
                <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu">
                <li class="@ViewBag.TicketNav">
                    <a href="@Url.Action("Index","Ticket")">
                        <i class="icon-double-angle-right"></i>
                        客票管理
                    </a>
                </li>
                <li class="@ViewBag.TicketUnionList">
                    <a href="@Url.Action("TicketUnionList", "Ticket")">
                        <i class="icon-double-angle-right"></i>
                        联运票管理
                    </a>

                </li>
                <li class="@ViewBag.TicketUnionBedList">
                    <a href="@Url.Action("TicketUnionBedList", "TicketUnionBed")" class="dropdown-toggle">
                        <i class="icon-double-angle-right"></i>
                        联管-满浦
                    </a>
                </li>
                <li class="@ViewBag.TicketGroupList">
                    <a href="@Url.Action("TicketGroupList", "TicketGroup")">
                        <i class="icon-double-angle-right"></i>
                        团体票管理
                    </a>
                </li>
                <li class="@ViewBag.TicketLaSaList">
                    <a href="@Url.Action("TicketLaSaList", "TicketLaSa")">
                        <i class="icon-double-angle-right"></i>
                        拉萨票管理
                    </a>
                </li>
            </ul>
        </li>
    }

    @if ((Model & 1) == 1 || (Model & 4) == 4 || (Model & 8) == 8 || (Model & 16) == 16 || (Model & 32) == 32)
    {
        <li class="@ViewBag.ReportNav">
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> 报表管理 </span>
                <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu">
                <li class="@ViewBag.GroupReportByDay">
                    <a href="@Url.Action("GroupReportByDay", "Report")">
                        <i class="icon-double-angle-right"></i>
                        集团日报
                    </a>
                </li>

                <li class="@ViewBag.GroupReportByWeek">
                    <a href="@Url.Action("GroupReportByWeek", "Report")">
                        <i class="icon-double-angle-right"></i>
                        集团周报
                    </a>
                </li>
                <li class="@ViewBag.GroupReportByMonth">
                    <a href="@Url.Action("GroupReportByMonth", "Report")">
                        <i class="icon-double-angle-right"></i>
                        集团月报
                    </a>
                </li>
                <li class="@ViewBag.TicketIncomManage">
                    <a href="@Url.Action("TicketIncomManage", "Report")">
                        <i class="icon-double-angle-right"></i>
                        经营分析报表
                    </a>
                </li>
                <li class="@ViewBag.TransportReportList">
                    <a href="@Url.Action("TransportReportList", "TransportReport")">
                        <i class="icon-double-angle-right"></i>
                        联运月报
                    </a>
                </li>
            </ul>
        </li>
    }

    <li class="@ViewBag.TicketNoticeNav">
        <a href="#" class="dropdown-toggle">
            <i class="icon-edit"></i>
            <span class="menu-text"> 电子公告板 </span>
            <b class="arrow icon-angle-down"></b>
        </a>
        <ul class="submenu">
            <li class="@ViewBag.TicketDetaileList">
                <a href="@Url.Action("TicketDetaileList", "TicketNotice")">
                    <i class="icon-double-angle-right"></i>
                    后台设置
                </a>
            </li>
            <li class="@ViewBag.TicketListManage">
                <a href="@Url.Action("TicketListManage", "TicketNotice")">
                    <i class="icon-double-angle-right"></i>
                    通知/电报
                </a>
            </li>
        </ul>
    </li>

    @if ((Model & 1) == 1 || (Model & 4) == 4 || (Model & 8) == 8 || (Model & 16) == 16 || (Model & 32) == 32)
    {
        <li class="@ViewBag.BaseDataNav">
            <a href="widgets.html" class="dropdown-toggle">
                <i class="icon-edit"></i>
                <span class="menu-text"> 基础信息维护 </span>
                <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu">
                @if ((Model & 1) == 1 || (Model & 16) == 16 || (Model & 32) == 32)
                {
                <li class="@ViewBag.GroupNav">
                    <a href="@Url.Action("GroupListManage", "Group")">
                        <i class="icon-double-angle-right"></i>
                        集团维护
                    </a>
                </li>
                }
                @if ((Model & 1) == 1 || (Model & 4) == 4 || (Model & 16) == 16 || (Model & 32) == 32)
                {
                <li class="@ViewBag.CompanyNav">
                    <a href="@Url.Action("CompanyListManage", "Company")">
                        <i class="icon-double-angle-right"></i>
                        单位维护
                    </a>
                </li>
                }
                @if ((Model & 1) == 1 || (Model & 4) == 4 || (Model & 8) == 8 || (Model & 16) == 16 || (Model & 32) == 32)
                {
                <li class="@ViewBag.SalePointListManage">
                    <a href="@Url.Action("SalePointListManage", "SalePoint")">
                        <i class="icon-double-angle-right"></i>
                        代售点维护
                    </a>
                </li>
                }
                @if ((Model & 1) == 1 || (Model & 4) == 4 || (Model & 8) == 8 || (Model & 16) == 16 || (Model & 32) == 32)
                {
                <li class="@ViewBag.PageNav">
                    <a href="@Url.Action("UserListManage", "UserInfo")">
                        <i class="icon-double-angle-right"></i>
                        人员维护
                    </a>
                </li>
                }
            </ul>
        </li>
    }
</ul>

TicketManage.WebSite/Views/Shared/_PartialMainTopNav.cshtml
<div class="navbar-header pull-right" role="navigation">
    <ul class="nav ace-nav">
        <li class="light-blue">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                <span class="user-info">
                    <small>欢迎光临</small>
                    @ViewBag.UserName
                </span>
                <i class="icon-caret-down"></i>
            </a>
            <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li>
                    <a title="" href="@Url.Action("ChangePassword", "UserInfoOther")">
                        <i class="icon-bar"></i>
                        修改密码
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Logout","Home")">
                        <i class="icon-off"></i>
                        退出
                    </a>
                </li>
            </ul>
        </li>
    </ul><!-- /.ace-nav -->
</div>

TicketManage.WebSite/Views/Shared/_PartialTopNav.cshtml
<div class="navbar-header pull-right" role="navigation">
    <ul class="nav ace-nav">
        <li class="light-blue">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                <span class="user-info">
                    <small>欢迎光临</small>
                    @ViewBag.UserName
                </span>
                <i class="icon-caret-down"></i>
            </a>
            <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li>
                    <a title="" href="@Url.Action("ChangePassword", "Home")">
                        <i class="icon-bar"></i>
                        修改密码
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Logout","Home")">
                        <i class="icon-off"></i>
                        退出
                    </a>
                </li>
            </ul>
        </li>
    </ul><!-- /.ace-nav -->
</div>