TicketManage.WebSite/Controllers/TravelLocalAgencyController.cs
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManage.Entity.CommonManage;
using TicketManage.Entity.TravelLocalAgencyManage;
using TicketManage.WebSite.Filters;
using TicketManage.WebSite.Logic;
using TicketManage.WebSite.Models;
using TieckManage.Biz.CommonManage;
using TieckManage.Biz.TravelLocalAgencyManage;

namespace TicketManage.WebSite.Controllers
{
    public class TravelLocalAgencyController : BaseController
    {

        private CommonBiz biz = new CommonBiz();
        /// <summary>
        /// 地接社业务实体
        /// </summary>
        private TravelLocalAgencyBiz tBiz = new TravelLocalAgencyBiz();

        [HttpGet]
        public ActionResult Login()
        {
            ViewBag.Title = "地接管理系统登录";
            var pageModel = new UserLoginPageModel();
            pageModel.MessageState = false;
            return View(pageModel);
        }

        [HttpPost]
        public ActionResult Login(UserLoginPageModel model)
        {
            ViewBag.Title = "地接管理系统登录";
            model.SysteCategory = SystemName.地接管理系统;
            model.SystemName = "地接管理系统";
            var result = biz.CommonLogin(model);
            if (result)
            {
                if (CheckUserAuth(model.PageModel.AuthNum, model.SysteCategory))
                {
                    Session[UserInfo] = model;
                    return RedirectToAction("TravelLocalAgencyList");
                }
                else
                {
                    model.Message = "您没有权限访问地接管理系统！";
                    model.MessageState = true;
                }
            }
            else
            {
                model.Message = "用户名密码错误！";
                model.MessageState = true;
            }
            return View(model);
        }

        #region 地接社信息管理

        /// <summary>
        /// 初始化查询区域需要数据源
        /// </summary>
        /// <param name="pageModel"></param>
        private void InitIndex(TravelLocalAgencyPageModel pageModel)
        {
            ViewBag.TravelLocalAgencyNav = "active open";
            ViewBag.TravelLocalAgencyListNav = "active";
            pageModel.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", pageModel.PageSize);
            pageModel.CategoryAreaSource = ConvertSystemCode(tBiz.GetSystemCodeListByType("CategoryArea"));
            pageModel.CategoryBizSource = ConvertSystemCode(tBiz.GetSystemCodeListByType("TravelArea"));
        }

        [HttpGet, LoginCheck]
        public ActionResult TravelLocalAgencyList()
        {
            var pageModel = new TravelLocalAgencyPageModel();
            pageModel.PageSize = 10;
            pageModel.CurrentPage = 1;
            InitIndex(pageModel);
            pageModel.ModelList = tBiz.GetTravelLocalAgencyByAll(pageModel);
            return View(pageModel);
        }

        [HttpPost, LoginCheck]
        public ActionResult TravelLocalAgencyList(TravelLocalAgencyPageModel model)
        {
            InitIndex(model);
            model.ModelList = tBiz.GetTravelLocalAgencyByCondition(model);
            return View(model);
        }

        [AjaxOnly, LoginCheck]
        public JsonResult TravelLocalAgencyDel(int id)
        {
            var result = tBiz.TravelLocalAgencyDel(id);
            return Json(new { result = result, message = result ? "删除成功！" : "未找到要删除数据！" });
        }

        [HttpGet, LoginCheck]
        public PartialViewResult TravelLocalAgencyAdd()
        {
            var pageModel = new TravelLocalAgencyPageModel();
            InitIndex(pageModel);
            pageModel.PageModel = new Repository.Models.TravelLocalAgency();
            pageModel.PageModel.TravelNo = String.Format("DJ_No{0}", DateTime.Now.ToString("yyyyMMddHHmmss"));
            pageModel.PageModel.Point = 60;
            return PartialView("_TravelLocalAgencyAdd", pageModel);
        }

        [HttpGet, LoginCheck]
        public PartialViewResult TravelLocalAgencyEdit(int id)
        {
            var pageModel = new TravelLocalAgencyPageModel();
            InitIndex(pageModel);
            pageModel.PageModel = tBiz.GetTravelLocalAgencyBySEQ(id);
            return PartialView("_TravelLocalAgencyAdd", pageModel);
        }

        [HttpPost, LoginCheck]
        public ActionResult TravelLocalAgencyEdit(TravelLocalAgencyPageModel model)
        {
            var uploadFile = base.FileUpload(Request);
            foreach (var item in uploadFile)
            {
                model.PageModel.CooperationInfo = item.Key;
            }
            var result = tBiz.TravelLocalAgencyEdit(model);
            return RedirectToAction("TravelLocalAgencyList");
        }


        #endregion

        #region 地接社比较管理

        private void TravelLocalAgencyCompareInit(TravelAgencyPageModel pageModel)
        {
            ViewBag.TravelLocalAgencyNav = "active open";
            ViewBag.TravelLocalAgencyCompareListNav = "active";
            var tempSource = new Dictionary<string, string>();
            for (int i = 0; i < 5; i++)
            {
                var year = DateTime.Now.Year - 2 + i;
                tempSource.Add(year.ToString(), year.ToString());
            }
            pageModel.RecordDateSource = new SelectList(tempSource, "Key", "Value", DateTime.Now.Year);
            pageModel.PageSizeList = new SelectList(PageSizeSource, "Key", "Value", pageModel.PageSize);
        }

        [HttpGet, LoginCheck]
        public ActionResult TravelLocalAgencyCompareList()
        {
            var pageModel = new TravelAgencyPageModel();
            pageModel.PageSize = 10;
            pageModel.CurrentPage = 1;
            TravelLocalAgencyCompareInit(pageModel);
            pageModel.ModelList = tBiz.GetTravelAgencyByAll(pageModel);
            var seqList = pageModel.ModelList.Select(a => a.SEQ).ToList();
            pageModel.PluginList = tBiz.GetTravelAreaPlugInByTravelAreaSEQ(seqList);
            return View(pageModel);
        }

        [HttpPost, LoginCheck]
        public ActionResult TravelLocalAgencyCompareList(TravelAgencyPageModel model)
        {
            TravelLocalAgencyCompareInit(model);
            model.ModelList = tBiz.GetTravelAgencyByCondition(model);
            var seqList = model.ModelList.Select(a => a.SEQ).ToList();
            model.PluginList = tBiz.GetTravelAreaPlugInByTravelAreaSEQ(seqList);
            return View(model);
        }

        [AjaxOnly, LoginCheck]
        public JsonResult TravelLocalAgencyCompareDel(int id)
        {
            var result = tBiz.TravelAgencyDel(id);
            return Json(new { result = result, message = result ? "删除成功！" : "删除失败！" });
        }

        [HttpGet, LoginCheck]
        public PartialViewResult TravelLocalAgencyCompareEdit(int? id)
        {
            var pageModel = new TravelAgencyPageModel();
            TicketManageLogic logic = new TicketManageLogic();
            if (id != null)
            {
                pageModel.PageModel = tBiz.GetTravelAgencyBySEQ(id ?? 0);
                pageModel.PluginList = tBiz.GetTravelAreaPlugInByTravelAreaSEQ(new List<int> { id ?? 0 });

                var tempRoomObj = pageModel.PluginList.Where(a => a.PlugInCategory == 1);
                if (tempRoomObj != null && tempRoomObj.Count() > 0)
                {
                    pageModel.RoomSummaryNum = tempRoomObj.Count();
                    pageModel.RoomSEQ = tempRoomObj.FirstOrDefault().SEQ;
                    pageModel.RoomSummaryText = tempRoomObj.FirstOrDefault().Summary;
                    pageModel.RoomPriceText = tempRoomObj.FirstOrDefault().PlugInPirce;
                }

                var tempFoodObj = pageModel.PluginList.Where(a => a.PlugInCategory == 2);
                if (tempFoodObj != null && tempFoodObj.Count() > 0)
                {
                    pageModel.FoodSummaryNum = tempFoodObj.Count();
                    pageModel.FoodSEQ = tempFoodObj.FirstOrDefault().SEQ;
                    pageModel.FoodSummaryText = tempFoodObj.FirstOrDefault().Summary;
                    pageModel.FoodPriceText = tempFoodObj.FirstOrDefault().PlugInPirce;
                }

                var tempCarObj = pageModel.PluginList.Where(a => a.PlugInCategory == 3);
                if (tempCarObj != null && tempCarObj.Count() > 0)
                {
                    pageModel.CarSummaryNum = tempCarObj.Count();
                    pageModel.CarSEQ = tempCarObj.FirstOrDefault().SEQ;
                    pageModel.CarSummaryText = tempCarObj.FirstOrDefault().Summary;
                    pageModel.CarPriceText = tempCarObj.FirstOrDefault().PlugInPirce;
                }


                pageModel.TravelAreaList = logic.CodeListToSelectList(tBiz.GetSystemCodeListByType("TravelArea"));
            }
            pageModel.TravelAreaList = logic.CodeListToSelectList(tBiz.GetSystemCodeListByType("TravelArea"));
            return PartialView("_TravelLocalAgencyCompareEdit", pageModel);
        }

        [HttpPost, LoginCheck]
        public ActionResult TravelLocalAgencyCompareEdit(TravelAgencyPageModel model)
        {
            model.PluginList = FileUploadByTravelAgency(Request);
            var fileModel = model.PluginList.Where(a => a.PlugInCategory == 4 && a.Summary == "PageModelPlugin.TravelAgencyFile").FirstOrDefault();
            if (fileModel != null)
            {
                model.PageModel.TravelAgencyFile = fileModel.FileContent;
            }
            model.PluginList.Remove(fileModel);
            tBiz.TravelAgencyEdit(model);
            return RedirectToAction("TravelLocalAgencyCompareList");
        }

        [AjaxOnly, LoginCheck]

TicketManage.WebSite/Views/TravelLocalAgency/Login.cshtml
@model TicketManage.Entity.CommonManage.UserLoginPageModel
@{
    ViewBag.Title = "地接管理系统登录";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@if (Model.MessageState)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        <strong>
            <i class="icon-remove"></i>
            @Model.Message
        </strong>
    </div>
}
@using (Html.BeginForm("Login", "TravelLocalAgency", FormMethod.Post, new { id = "LoginForm" }))
{
    <fieldset>
        <label class="block clearfix">
            <span class="block input-icon input-icon-right">
                @Html.TextBoxFor(a => a.PageModel.UserNo, new { @class = "form-control", placeholder = "Username" })
                <i class="icon-user"></i>
            </span>
        </label>

        <label class="block clearfix">
            <span class="block input-icon input-icon-right">
                @Html.PasswordFor(a => a.PageModel.UserPassword, new { @class = "form-control", placeholder = "Password", onkeydown = "return LoginCheck(event)" })
                <i class="icon-lock"></i>
            </span>
        </label>

        <div class="space"></div>

        <div class="clearfix">
            <label class="inline">
                <input type="checkbox" class="ace" id="rememberFlag" />
                <span class="lbl" style="cursor:pointer;"> 记住密码</span>
            </label>
            <button type="button" id="LoginBut" class="width-35 pull-right btn btn-sm btn-primary">
                <i class="icon-key"></i>
                登录
            </button>

        </div>

        <div class="space-4"></div>
    </fieldset>
}

TicketManage.WebSite/Views/TravelLocalAgency/MeetingRecordList.cshtml
@model TicketManage.Entity.TravelLocalAgencyManage.MeetingInfoPageModel
@{
    ViewBag.Title = "会议记录列表";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    var IndexCount = 1;
}
@section HeaderScript{
    <link href="~/Scripts/skin/WdatePicker.css" rel="stylesheet" />
    <script src="~/Scripts/WdatePicker.js"></script>
    <script src="~/Content/js/bootbox.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#Previous").click(function () {
                var num = $("#currentPageNum").find("a").prop("title");
                var converNum = parseInt(num);
                if (converNum > 1) {
                    SubmitSearchForm(converNum - 1);
                }
            });
            $("#Next").click(function () {
                var num = $("#currentPageNum").find("a").prop("title");
                var converNum = parseInt(num);
                var maxNum = parseInt(@Model.PageTotal);
                if (converNum < maxNum) {
                    SubmitSearchForm(converNum + 1);
                }
            });
            $("#pagination").find("a[id*='pageNum_']").click(function () {
                SubmitSearchForm($(this).prop("title"));
            });
            $("#btnSearch").click(function () {
                SubmitSearchForm();
            });
            $("#pageSizeList").change(function () {
                SubmitSearchForm();
            });
            $("#sumitForm").click(function () {
                $("#MeetingRecordEditForm").submit();
            });



            $("#btnAdd").click(function () {
                $.ajax({
                    url: "@Url.Action("MeetingRecordEdit", "TravelLocalAgency")",
                    cache: false,
                    type: "GET",
                    success: function (result) {
                        $("#addMeetingRecordBody").html(result);
                        $("#MeetingRecordModal").modal("toggle");
                    }, error: function (q, w, e) {
                        alert(q + w + e);
                    }
                });
            });

            $("#sample-table-1").find("button[id*='editBtn_']").click(function () {
                var clickDelNum = $(this).prop("title");
                $.ajax({
                    url: "@Url.Action("MeetingRecordEdit", "TravelLocalAgency")",
                    cache: false,
                    type: "GET",
                    data: { id: clickDelNum },
                    success: function (result) {
                        $("#addMeetingRecordBody").html(result);
                        $("#MeetingRecordModal").modal("toggle");
                    }, error: function (q, w, e) {
                        alert(q + w + e);
                    }
                });
            });


            function SubmitSearchForm(currentPage) {
                if (currentPage == undefined) {
                    $("#CurrentPage").val();
                } else {
                    $("#CurrentPage").val(currentPage);
                }
                $("#PageSize").val($("#pageSizeList").val());
                $("#MeetingRecordListSearchForm").submit();
            }

            $("button[id*='bootbox-confirm_']").each(function () {
                $(this).click(function () {
                    var obj = $(this);
                    var clickDelNum = $(this).prop("title");
                    bootbox.confirm("是否确认删除?", function (result) {
                        if (result) {
                            $.ajax({
                                url: "@Url.Action("MeetingRecordDel", "TravelLocalAgency")",
                                type: "GET",
                                data: { id: clickDelNum },
                                success: function (json) {
                                    $(obj).parent().parent().remove();
                                },
                                error: function (q, w, e) {
                                    alert(q + w + e);
                                }
                            });
                        }
                    });
                });
            });

            $("button[id*='bootbox-confirm_']").each(function () {
                $(this).click(function () {
                    var obj = $(this);
                    var clickDelNum = $(this).prop("title");
                    bootbox.confirm("是否确认删除?", function (result) {
                        if (result) {
                            $.ajax({
                                url: "@Url.Action("MeetingRecordDel", "TravelLocalAgency")",
                                type: "GET",
                                data: { id: clickDelNum },
                                success: function (json) {
                                    $(obj).parent().parent().remove();
                                },
                                error: function (q, w, e) {
                                    alert(q + w + e);
                                }
                            });
                        }
                    });
                });
            });
        })
    </script>
}
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="@Url.Action("MeetingRecordList", "TravelLocalAgency")">地接管理系统</a>
        </li>
        <li>
            <a href="@Url.Action("MeetingRecordList", "TravelLocalAgency")">会议记录管理</a>
        </li>
        <li class="active">会议记录列表</li>
    </ul><!-- .breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            会议记录列表
        </h1>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <div class="clearfix">
                    <form action="@Url.Action("MeetingRecordList", "TravelLocalAgency")" method="post" id="MeetingRecordListSearchForm">
                        @Html.HiddenFor(a => a.PageSize)
                        @Html.HiddenFor(a => a.CurrentPage)
                        <div class="col-md-1" style="line-height: 33px; text-align: right">
                            <label class=" control-label no-padding-right" style="">标题：</label>
                        </div>
                        <div class="col-md-2" id="CompanyListArea">
                            @Html.TextBoxFor(a => a.PageModel.MeetingTitle, new { @class = "form-control" })
                        </div>
                        <div class="col-md-1" style="line-height: 33px; text-align: right">
                            <label class="control-label no-padding-right">参加人员：</label>
                        </div>
                        <div class="col-md-2">
                            <span>
                                @Html.TextBoxFor(a => a.PageModel.PersonDetial, new { @class = "form-control" })
                            </span>
                        </div>
                        <div class="col-md-2" style="line-height: 33px; text-align: right">

                        </div>

                    </form>
                    <div class="col-md-4">
                        <button class="btn btn-purple btn-sm" id="btnSearch"><i class="icon-search icon-on-right bigger-110"></i>查询</button>
                        @if ((Model.OperatorAuthNum & 16384) == 16384)
                        {
                            <button class="btn btn-pink btn-sm" id="btnAdd">数据录入</button>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>标题</th>
                            <th>会议日期</th>
                            <th>参加人员</th>
                            <th>会议内容</th>
                            <th>附件</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ModelList)
                        {
                            <tr>
                                <td>
                                    <a href="#">@(IndexCount++)</a>
                                </td>
                                <td>@item.MeetingTitle</td>
                                <td>@Model.ConvertDateTime(item.MeetingDate)</td>
                                <td>@item.PersonDetial</td>
                                <td>@item.MeetingContent</td>
                                <td>
                                    @if (!string.IsNullOrEmpty(item.FileInfo))
                                    {
                                        <a class="btn btn-sm btn-info" href="~/UploadFile/@item.FileInfo">附件下载</a>
                                    }
                                    else
                                    {
                                        <span>未上传附件</span>
                                    }
                                </td>
                                <td>
                                    @if ((Model.OperatorAuthNum & 16384) == 16384)
                                    {
                                        <button class="btn btn-sm btn-warning" id="editBtn_@item.SEQ" title="@item.SEQ" type="button">编辑</button>
                                        <button class="btn btn-sm btn-danger" title="@item.SEQ" id="bootbox-confirm_@item.SEQ" type="button">删除</button>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row" style="background-color:#f5f5f5;border:1px solid #e3e3e3;margin-left:0px;margin-right:0px">
        <div class="col-xs-6">
            <div style="color:#2283c5;padding-top:5px">
                <label class="text-info" style="margin-top:3px">每页显示</label>
                @Html.DropDownListFor(a => a.PageSize, Model.PageSizeList, new { id = "pageSizeList", style = "margin-bottom:4px" })
                <label class="text-info" style="margin-top:3px">条记录</label>
                <label class="text-info" style="margin-top:3px">共 @Model.PageNum 项</label>
            </div>
        </div>
        <div class="col-xs-6 text-right" style="padding-top:5px">
            <ul id="pagination" class="pagination" style="margin:0px">
                <li>
                    <a id="Previous" aria-label="Previous">
                        <span aria-hidden="true" style="cursor:pointer">上一页</span>
                    </a>
                </li>
                @for (int i = 1; i <= Model.PageTotal; i++)
                {
                    if (Model.CurrentPage == i)
                    {
                        <li id="currentPageNum"><a style="background-color: #428bca;color:#f5f5f5;cursor:pointer" title="@i" id="pageNum_@i">@i</a></li>
                    }
                    else
                    {
                        <li><a style="cursor: pointer; " id="pageNum_@i" title="@i">@i</a></li>
                    }
                }
                <li>
                    <a id="Next" aria-label="Next">
                        <span aria-hidden="true" style="cursor:pointer">下一页</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="modal fade" id="MeetingRecordModal" tabindex="-1" role="dialog" aria-labelledby="myModalMeetingRecordListLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalMeetingRecordListLabel">
                    会议记录信息
                </h4>
            </div>
            <div class="modal-body">
                <div id="addMeetingRecordBody" class="page-content">

                </div>
            </div>
            <div class="modal-footer">
                <input type="button" id="sumitForm" class="btn btn-info btn-sm" style="margin-right:10px" value="保存" />
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

TicketManage.WebSite/Views/TravelLocalAgency/_MeetingRecordEdit.cshtml
@model TicketManage.Entity.TravelLocalAgencyManage.MeetingInfoPageModel
<div id="addUserInfoArea" class="page-content">
    <div class="row">
        <div class="col-lg-12">
            <form class="form-horizontal" action="@Url.Action("MeetingRecordFormEdit", "TravelLocalAgency")" method="post" role="form" id="MeetingRecordEditForm" enctype="multipart/form-data">
                @Html.HiddenFor(p => p.PageModel.SEQ)
                @Html.HiddenFor(a => a.PageModel.OperatorSEQ)
                @Html.HiddenFor(a => a.PageModel.OperatorName)
                @Html.HiddenFor(a => a.PageModel.CreateTime)
                @Html.HiddenFor(a => a.PageModel.FileInfo)
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">标题：</label>
                    <div class="col-sm-9" style="text-align:left">
                        @Html.TextBoxFor(a => a.PageModel.MeetingTitle, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 会议日期：</label>
                    <div class="col-sm-9" style="text-align:left;">
                        @Html.TextBoxFor(a => a.PageModel.MeetingDate, new { @class = "form-control", onfocus = "WdatePicker()" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">参加人员：</label>
                    <div class="col-sm-9" style="text-align:left">
                        @Html.TextBoxFor(a => a.PageModel.PersonDetial, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">会议内容：</label>
                    <div class="col-sm-9" id="SalePointListArea">
                        @Html.TextBoxFor(a => a.PageModel.MeetingContent, new { @class = "form-control" })
                    </div>
                </div>
                <div id="fileUploadArea" class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">上传附件：</label>
                    <div class="col-sm-9">
                        <input type="file" name="FileName" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red;text-align:left"></label>
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red" id="MessageArea"></label>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="fileUploadHide" style="display:none">
    <div title="pageAddFile" class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"></label>
        <div class="col-sm-9">
            <input type="file" name="FileName" class="form-control" />
        </div>
    </div>
</div>

TicketManage.WebSite/Views/TravelLocalAgency/_TravelAreaEdit.cshtml
@model TicketManage.Entity.TravelLocalAgencyManage.TravelAreaListPageModel
<div id="addUserInfoArea" class="page-content">
    <div class="row">
        <div class="col-lg-12">
            <form class="form-horizontal" action="@Url.Action("TravelAreaEdit", "TravelLocalAgency")" method="post" role="form" id="TravelAreaEditForm">
                @Html.HiddenFor(p => p.PageModel.SEQ)
                @Html.HiddenFor(a => a.PageModel.CodeNo)
                @Html.HiddenFor(a => a.PageModel.CategoryNo)
                @Html.HiddenFor(a => a.PageModel.CategoryName)
                @Html.HiddenFor(a => a.PageModel.IsParent)
                @Html.HiddenFor(a => a.PageModel.ParentCodeNo)
                @Html.HiddenFor(a => a.PageModel.Memo)
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">业务范围：</label>
                    <div class="col-sm-9" style="text-align:left">
                        @Html.TextBoxFor(a => a.PageModel.CodeName, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red;text-align:left"></label>
                    <label class="col-sm-6 control-label no-padding-right" for="form-field-1" style="color:red" id="MessageArea"></label>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="fileUploadHide" style="display:none">
    <div title="pageAddFile" class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"></label>
        <div class="col-sm-9">
            <input type="file" name="FileName" class="form-control" />
        </div>
    </div>
</div>